/* Parameters for ./mpn/generic/gmp-mparam.h
 * Using: CPU cycle counter
 * speed_precision 10000, speed_unittime 1 cycle, CPU freq unknown
 * DEFAULT_MAX_SIZE 1000, fft_max_size 50000
 */
 
/* Generated by tuneup.c, 2026-06-14, MS Visual C/C++ (64bit) MMNNBBBBB=195236418, rev. 1 */

#define MOD_1_1P_METHOD                      2  /* 37.90% faster than 1 */
#define MOD_1_NORM_THRESHOLD                43
#define MOD_1_UNNORM_THRESHOLD              86
#define MOD_1N_TO_MOD_1_1_THRESHOLD         18
#define MOD_1U_TO_MOD_1_1_THRESHOLD         15
#define MOD_1_1_TO_MOD_1_2_THRESHOLD         0  /* never mpn_mod_1_1p */
#define MOD_1_2_TO_MOD_1_4_THRESHOLD        21
#define PREINV_MOD_1_TO_MOD_1_THRESHOLD      3
#define USE_PREINV_DIVREM_1                  1  /* native */
#define DIV_QR_1N_PI1_METHOD                 1  /* 1.24% faster than 4 */
#define DIV_QR_1_NORM_THRESHOLD             29
#define DIV_QR_1_UNNORM_THRESHOLD           27
#define DIV_QR_2_PI2_THRESHOLD              14
#define DIVEXACT_1_THRESHOLD             MP_SIZE_T_MAX  /* never */
#define BMOD_1_TO_MOD_1_THRESHOLD           19

#define DIV_1_VS_MUL_1_PERCENT             584

#define MUL_TOOM22_THRESHOLD                24
#define MUL_TOOM33_THRESHOLD                29
#define MUL_TOOM44_THRESHOLD               100
#define MUL_TOOM6H_THRESHOLD               108
#define MUL_TOOM8H_THRESHOLD               167

#define MUL_TOOM32_TO_TOOM43_THRESHOLD      60
#define MUL_TOOM32_TO_TOOM53_THRESHOLD      54
#define MUL_TOOM42_TO_TOOM53_THRESHOLD     100
#define MUL_TOOM42_TO_TOOM63_THRESHOLD      96
#define MUL_TOOM43_TO_TOOM54_THRESHOLD     136

#define SQR_BASECASE_THRESHOLD               0  /* always (native) */
#define SQR_TOOM2_THRESHOLD                 23
#define SQR_TOOM3_THRESHOLD                 44
#define SQR_TOOM4_THRESHOLD                384
#define SQR_TOOM6_THRESHOLD                522
#define SQR_TOOM8_THRESHOLD                632

#define MULMID_TOOM42_THRESHOLD             31

#define MULMOD_BNM1_THRESHOLD               14
#define SQRMOD_BNM1_THRESHOLD               14

#define MUL_FFT_MODF_THRESHOLD             276  /* k = 5 */
#define MUL_FFT_TABLE3                                      \
  { {    276, 5}, {      9, 4}, {     19, 5}, {     11, 4}, \
    {     23, 6}, {      6, 5}, {     13, 6}, {      7, 5}, \
    {     16, 6}, {      9, 5}, {     21, 6}, {     17, 7}, \
    {      9, 6}, {     21, 7}, {     15, 6}, {     32, 8}, \
    {      9, 7}, {     21, 8}, {     11, 7}, {     23, 8}, \
    {     13, 7}, {     28, 8}, {     15, 7}, {     33, 8}, \
    {     17, 7}, {     36, 8}, {     21, 9}, {     11, 8}, \
    {     25, 9}, {     15, 8}, {     35, 9}, {     19, 8}, \
    {     39, 9}, {     23, 8}, {     49,10}, {     15, 9}, \
    {     39,10}, {     23, 9}, {     51,11}, {     15,10}, \
    {     39, 9}, {     79,10}, {   1024,11}, {   2048,12}, \
    {   4096,13}, {   8192,14}, {  16384,15}, {  32768,16} }
#define MUL_FFT_TABLE3_SIZE 48
#define MUL_FFT_THRESHOLD                 1376

#define SQR_FFT_MODF_THRESHOLD             304  /* k = 5 */
#define SQR_FFT_TABLE3                                      \
  { {    304, 5}, {     16, 6}, {     10, 5}, {     21, 6}, \
    {     19, 7}, {     10, 6}, {     21, 7}, {     17, 8}, \
    {      9, 7}, {     21, 8}, {     21, 9}, {     11, 8}, \
    {     23, 7}, {     47, 8}, {     25, 9}, {     19, 8}, \
    {     41, 9}, {     23, 8}, {     47,10}, {     15, 9}, \
    {     43,10}, {     23, 9}, {     51,11}, {     15,10}, \
    {     31, 9}, {     63,10}, {     39, 9}, {     79,10}, \
    {     47, 9}, {     95,10}, {   1024,11}, {   2048,12}, \
    {   4096,13}, {   8192,14}, {  16384,15}, {  32768,16} }
#define SQR_FFT_TABLE3_SIZE 36
#define SQR_FFT_THRESHOLD                 1856

#define MULLO_BASECASE_THRESHOLD             0  /* always */
#define MULLO_DC_THRESHOLD                  28
#define MULLO_MUL_N_THRESHOLD             2742
#define SQRLO_BASECASE_THRESHOLD             6
#define SQRLO_DC_THRESHOLD                 108
#define SQRLO_SQR_THRESHOLD               3690

#define DC_DIV_QR_THRESHOLD                 72
#define DC_DIVAPPR_Q_THRESHOLD              81
#define DC_BDIV_QR_THRESHOLD                 8
#define DC_BDIV_Q_THRESHOLD                 17

#define INV_MULMOD_BNM1_THRESHOLD           92
#define INV_NEWTON_THRESHOLD                14
#define INV_APPR_THRESHOLD                   7

#define BINV_NEWTON_THRESHOLD               11
#define REDC_1_TO_REDC_N_THRESHOLD          68

#define MU_DIV_QR_THRESHOLD                748
#define MU_DIVAPPR_Q_THRESHOLD             748
#define MUPI_DIV_QR_THRESHOLD                7
#define MU_BDIV_QR_THRESHOLD                15
#define MU_BDIV_Q_THRESHOLD                872

#define POWM_SEC_TABLE  8,30,71,579,904

#define GET_STR_DC_THRESHOLD                16
#define GET_STR_PRECOMPUTE_THRESHOLD        23
#define SET_STR_DC_THRESHOLD               286
#define SET_STR_PRECOMPUTE_THRESHOLD      2826

#define FAC_DSC_THRESHOLD                  234
#define FAC_ODD_THRESHOLD                    0  /* always */

#define MATRIX22_STRASSEN_THRESHOLD         12
#define HGCD2_DIV1_METHOD                    1  /* 2.75% faster than 5 */
#define HGCD_THRESHOLD                     141
#define HGCD_APPR_THRESHOLD                147
#define HGCD_REDUCE_THRESHOLD             1437
#define GCD_DC_THRESHOLD                   250
#define GCDEXT_DC_THRESHOLD                411
#define JACOBI_BASE_METHOD                   1  /* 27.91% faster than 3 */

/* Tuneup completed successfully, took 39 seconds */