; Copyright 2003-2026 Free Software Foundation, Inc.
;
; This file is part of the GNU MP Library (MS Windows port).
;
; The GNU MP Library is free software; you can redistribute it and/or modify
; it under the terms of either:
;
;   * the GNU Lesser General Public License as published by the Free
;     Software Foundation; either version 3 of the License, or (at your
;     option) any later version.
;
; or
;
;   * the GNU General Public License as published by the Free Software
;     Foundation; either version 2 of the License, or (at your option) any
;     later version.
;
; or both in parallel, as here.
;
; The GNU MP Library is distributed in the hope that it will be useful, but
; WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
; or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU General Public License
; for more details.
;
; You should have received copies of the GNU General Public License and the
; GNU Lesser General Public License along with the GNU MP Library.  If not,
; see https://www.gnu.org/licenses/.
;
; The System V AMD64 ABI (gcc) was converted by Ingo A. Kubbilun
; <ingo.kubbilun@gmail.com> at 05/01/2026 to the MS Visual C/C++ 64bit ABI.
; The MS Visual C/C++ 64bit ABI heavily differs from the System V AMD64 ABI.
; (with greetings from good 'old' Germany)...
;
; Some register renamings WOULD HAVE BEEN helped reducing the ABI compatibility
; prologue or epilogue, respectively (TODO - although this is small O(1)
; overhead, i.e. just a small bunch of extra CPU cycles).
;

                   .CODE

                    ALIGN 16

__gmpn_sqr_basecase PROC

         push   rdi                           ; SysV-to-MSVC ABI (save rdi)
         push   rsi                           ; SysV-to-MSVC ABI (save rsi)
                                              ; function parameter #1 in RCX (gcc assumes RDI)
                                              ; function parameter #2 in RDX (gcc assumes RSI)
                                              ; function parameter #3 in R8 (gcc assumes RDX)
         mov    rdi,rcx                       ; SysV-to-MSVC ABI (parameter #1 from rcx to rdi)
         mov    rsi,rdx                       ; SysV-to-MSVC ABI (parameter #2 from rdx to rsi)
         mov    rdx,r8                        ; SysV-to-MSVC ABI (parameter #3 from r8 to rdx)
         cmp    rdx,02h                       ; 
         jae    l_0016                        ; 
         mov    rdx,qword ptr [rsi]           ; 
         mulx   rdx,rax,rdx                   ; 
         mov    qword ptr [rdi],rax           ; 
         mov    qword ptr [rdi+08h],rdx       ; 
         pop    rsi                           ; SysV-to-MSVC ABI (restore rsi)
         pop    rdi                           ; SysV-to-MSVC ABI (restore rdi)
         ret                                  ; 
         ALIGN  16                            ;
l_0016:  jne    l_0055                        ; 
         mov    rdx,qword ptr [rsi]           ; 
         mov    rcx,qword ptr [rsi+08h]       ; 
         mulx   r10,r9,rcx                    ; 
         mulx   r8,rax,rdx                    ; 
         mov    rdx,rcx                       ; 
         mulx   rdx,r11,rdx                   ; 
         add    r9,r9                         ; 
         adc    r10,r10                       ; 
         adc    rdx,00h                       ; 
         add    r8,r9                         ; 
         adc    r10,r11                       ; 
         adc    rdx,00h                       ; 
         mov    qword ptr [rdi],rax           ; 
         mov    qword ptr [rdi+08h],r8        ; 
         mov    qword ptr [rdi+010h],r10      ; 
         mov    qword ptr [rdi+018h],rdx      ; 
         pop    rsi                           ; SysV-to-MSVC ABI (restore rsi)
         pop    rdi                           ; SysV-to-MSVC ABI (restore rdi)
         ret                                  ; 
         ALIGN  16                            ;
l_0055:  cmp    rdx,04h                       ; 
         jae    l_00FA                        ; 
         push   rbx                           ; 
         mov    rdx,qword ptr [rsi]           ; 
         mulx   r11,r10,qword ptr [rsi+08h]   ; 
         mulx   r9,r8,qword ptr [rsi+010h]    ; 
         add    r8,r11                        ; 
         mov    rdx,qword ptr [rsi+08h]       ; 
         mulx   r11,rax,qword ptr [rsi+010h]  ; 
         adc    r9,rax                        ; 
         adc    r11,00h                       ; 
         test   ebx,ebx                       ; 
         mov    rdx,qword ptr [rsi]           ; 
         mulx   rcx,rbx,rdx                   ; 
         mov    qword ptr [rdi],rbx           ; 
         mov    rdx,qword ptr [rsi+08h]       ; 
         mulx   rbx,rax,rdx                   ; 
         mov    rdx,qword ptr [rsi+010h]      ; 
         mulx   rdx,rsi,rdx                   ; 
         adcx   r10,r10                       ; 
         adcx   r8,r8                         ; 
         adcx   r9,r9                         ; 
         adcx   r11,r11                       ; 
         adox   rcx,r10                       ; 
         adox   rax,r8                        ; 
         adox   rbx,r9                        ; 
         adox   rsi,r11                       ; 
         mov    r8d,00h                       ; 
         adox   rdx,r8                        ; 
         adcx   rdx,r8                        ; 
         mov    qword ptr [rdi+08h],rcx       ; 
         mov    qword ptr [rdi+010h],rax      ; 
         mov    qword ptr [rdi+018h],rbx      ; 
         mov    qword ptr [rdi+020h],rsi      ; 
         mov    qword ptr [rdi+028h],rdx      ; 
         pop    rbx                           ; 
         pop    rsi                           ; SysV-to-MSVC ABI (restore rsi)
         pop    rdi                           ; SysV-to-MSVC ABI (restore rdi)
         ret                                  ; 
         ALIGN  16                            ;
l_00FA:  push   rbx                           ; 
         lea    ebx,[rdx-03h]                 ; 
         lea    ecx,[rdx+05h]                 ; 
         mov    eax,edx                       ; 
         and    ebx,0fffffff8h                ; 
         shr    ecx,03h                       ; 
         neg    rbx                           ; 
         and    eax,07h                       ; 
         mov    rdx,qword ptr [rsi]           ; 
         mov    r10,offset Lmtab              ; 
         jmp    qword ptr [r10+rax*8]         ; 
         ALIGN  16                            ;
Lmf0:    mulx   r9,r8,rdx                     ; 
         add    rdx,rdx                       ; 
         mulx   r11,r10,qword ptr [rsi+08h]   ; 
         lea    rsi,[rsi+040h]                ; 
         add    r10,r9                        ; 
         jmp    l_0234                        ; 
         ALIGN  16                            ;
Lmf3:    mulx   r11,r10,rdx                   ; 
         add    rdx,rdx                       ; 
         mov    qword ptr [rdi],r10           ; 
         mulx   r9,r8,qword ptr [rsi+08h]     ; 
         lea    rsi,[rsi+018h]                ; 
         lea    rdi,[rdi+018h]                ; 
         add    r8,r11                        ; 
         jmp    l_027C                        ; 
         ALIGN  16                            ;
Lmf4:    mulx   r9,r8,rdx                     ; 
         add    rdx,rdx                       ; 
         mulx   r11,r10,qword ptr [rsi+08h]   ; 
         mov    qword ptr [rdi],r8            ; 
         lea    rsi,[rsi+020h]                ; 
         lea    rdi,[rdi+020h]                ; 
         add    r10,r9                        ; 
         jmp    l_026F                        ; 
         ALIGN  16                            ;
Lmf5:    mulx   r11,r10,rdx                   ; 
         add    rdx,rdx                       ; 
         mulx   r9,r8,qword ptr [rsi+08h]     ; 
         mov    qword ptr [rdi],r10           ; 
         lea    rsi,[rsi+028h]                ; 
         lea    rdi,[rdi+028h]                ; 
         add    r8,r11                        ; 
         jmp    l_0262                        ; 
         ALIGN  16                            ;
Lmf6:    mulx   r9,r8,rdx                     ; 
         add    rdx,rdx                       ; 
         mulx   r11,r10,qword ptr [rsi+08h]   ; 
         mov    qword ptr [rdi],r8            ; 
         lea    rsi,[rsi+030h]                ; 
         lea    rdi,[rdi+030h]                ; 
         add    r10,r9                        ; 
         jmp    l_0255                        ; 
         ALIGN  16                            ;
Lmf7:    mulx   r11,r10,rdx                   ; 
         add    rdx,rdx                       ; 
         mulx   r9,r8,qword ptr [rsi+08h]     ; 
         mov    qword ptr [rdi],r10           ; 
         lea    rsi,[rsi+038h]                ; 
         lea    rdi,[rdi+038h]                ; 
         add    r8,r11                        ; 
         jmp    l_0248                        ; 
         ALIGN  16                            ;
Lmf1:    mulx   r11,r10,rdx                   ; 
         add    rdx,rdx                       ; 
         mulx   r9,r8,qword ptr [rsi+08h]     ; 
         mov    qword ptr [rdi],r10           ; 
         lea    rsi,[rsi+08h]                 ; 
         lea    rdi,[rdi+08h]                 ; 
         add    r8,r11                        ; 
         jmp    l_0227                        ; 
         ALIGN  16                            ;
Lmf2:    mulx   r9,r8,rdx                     ; 
         add    rdx,rdx                       ; 
         mulx   r11,r10,qword ptr [rsi+08h]   ; 
         mov    qword ptr [rdi],r8            ; 
         lea    rsi,[rsi+010h]                ; 
         lea    rdi,[rdi+010h]                ; 
         dec    ecx                           ; 
         add    r10,r9                        ; 
         mulx   r9,r8,qword ptr [rsi]         ; 
         ALIGN  16                            ; 
Ltop:    mov    qword ptr [rdi-08h],r10       ; 
         adc    r8,r11                        ; 
l_0227:  mulx   r11,r10,qword ptr [rsi+08h]   ; 
         adc    r10,r9                        ; 
         lea    rsi,[rsi+040h]                ; 
l_0234:  mov    qword ptr [rdi],r8            ; 
         mov    qword ptr [rdi+08h],r10       ; 
         mulx   r9,r8,qword ptr [rsi-030h]    ; 
         lea    rdi,[rdi+040h]                ; 
         adc    r8,r11                        ; 
l_0248:  mulx   r11,r10,qword ptr [rsi-028h]  ; 
         mov    qword ptr [rdi-030h],r8       ; 
         adc    r10,r9                        ; 
l_0255:  mov    qword ptr [rdi-028h],r10      ; 
         mulx   r9,r8,qword ptr [rsi-020h]    ; 
         adc    r8,r11                        ; 
l_0262:  mulx   r11,r10,qword ptr [rsi-018h]  ; 
         mov    qword ptr [rdi-020h],r8       ; 
         adc    r10,r9                        ; 
l_026F:  mulx   r9,r8,qword ptr [rsi-010h]    ; 
         mov    qword ptr [rdi-018h],r10      ; 
         adc    r8,r11                        ; 
l_027C:  mulx   r11,r10,qword ptr [rsi-08h]   ; 
         adc    r10,r9                        ; 
         mov    qword ptr [rdi-010h],r8       ; 
         dec    ecx                           ; 
         mulx   r9,r8,qword ptr [rsi]         ; 
         jne    Ltop                          ; 
         mov    qword ptr [rdi-08h],r10       ; 
         adc    r8,r11                        ; 
         mov    r10,offset Latab              ; 
         mov    r11,qword ptr [r10+rax*8]     ; 
         mov    eax,03fh                      ; 
         jmp    r11                           ; 
         ALIGN  16                            ;
l_02AC:  adox   r8,qword ptr [rdi]            ; 
         adox   r9,rcx                        ; 
Lf7:     mov    qword ptr [rdi],r8            ; 
         adc    r9,rcx                        ; 
         mov    qword ptr [rdi+08h],r9        ; 
         lea    rsi,[rsi+rbx*8-040h]          ; 
         mov    ecx,ebx                       ; 
         lea    rdi,[rdi+rbx*8-038h]          ; 
         mov    r9,qword ptr [rsi]            ; 
         mov    rdx,qword ptr [rsi+08h]       ; 
         shrx   r8,r9,rax                     ; 
         sarx   r9,r9,rax                     ; 
         and    r9,rdx                        ; 
         mulx   r11,r10,rdx                   ; 
         lea    rdx,[r8+rdx*2]                ; 
         jmp    l_0B05                        ; 
         ALIGN  16                            ;
l_02F0:  adox   r10,qword ptr [rdi-08h]       ; 
         adcx   r8,r11                        ; 
         mov    qword ptr [rdi-08h],r10       ; 
         jrcxz  l_02AC                        ; 
         mulx   r11,r10,qword ptr [rsi+08h]   ; 
         adox   r8,qword ptr [rdi]            ; 
         lea    ecx,[rcx+08h]                 ; 
l_0312:  mov    qword ptr [rdi],r8            ; 
         adcx   r10,r9                        ; 
         mulx   r9,r8,qword ptr [rsi+010h]    ; 
         adcx   r8,r11                        ; 
         adox   r10,qword ptr [rdi+08h]       ; 
         mov    qword ptr [rdi+08h],r10       ; 
         mulx   r11,r10,qword ptr [rsi+018h]  ; 
         lea    rsi,[rsi+040h]                ; 
         adcx   r10,r9                        ; 
         adox   r8,qword ptr [rdi+010h]       ; 
         mov    qword ptr [rdi+010h],r8       ; 
         mulx   r9,r8,qword ptr [rsi-020h]    ; 
         adox   r10,qword ptr [rdi+018h]      ; 
         adcx   r8,r11                        ; 
         mov    qword ptr [rdi+018h],r10      ; 
         mulx   r11,r10,qword ptr [rsi-018h]  ; 
         adcx   r10,r9                        ; 
         adox   r8,qword ptr [rdi+020h]       ; 
         mov    qword ptr [rdi+020h],r8       ; 
         mulx   r9,r8,qword ptr [rsi-010h]    ; 
         adox   r10,qword ptr [rdi+028h]      ; 
         adcx   r8,r11                        ; 
         mov    qword ptr [rdi+028h],r10      ; 
         adox   r8,qword ptr [rdi+030h]       ; 
         mulx   r11,r10,qword ptr [rsi-08h]   ; 
         mov    qword ptr [rdi+030h],r8       ; 
         lea    rdi,[rdi+040h]                ; 
         adcx   r10,r9                        ; 
         mulx   r9,r8,qword ptr [rsi]         ; 
         jmp    l_02F0                        ; 
         ALIGN  16                            ;
l_03B7:  adox   r8,qword ptr [rdi]            ; 
         adox   r9,rcx                        ; 
Lf0:     mov    qword ptr [rdi],r8            ; 
         adc    r9,rcx                        ; 
         mov    qword ptr [rdi+08h],r9        ; 
         lea    rsi,[rsi+rbx*8-040h]          ; 
         mov    ecx,ebx                       ; 
         lea    rdi,[rdi+rbx*8-038h]          ; 
         mov    r11,qword ptr [rsi-08h]       ; 
         mov    rdx,qword ptr [rsi]           ; 
         shrx   r10,r11,rax                   ; 
         sarx   r11,r11,rax                   ; 
         and    r11,rdx                       ; 
         mulx   r9,r8,rdx                     ; 
         lea    rdx,[r10+rdx*2]               ; 
         adcx   r8,r11                        ; 
         mulx   r11,r10,qword ptr [rsi+08h]   ; 
         adox   r8,qword ptr [rdi]            ; 
         jmp    l_0312                        ; 
         ALIGN  16                            ; 
l_0410:  adox   r10,qword ptr [rdi-08h]       ; 
         adcx   r8,r11                        ; 
         mov    qword ptr [rdi-08h],r10       ; 
         jrcxz  l_03B7                        ; 
l_0423:  mulx   r11,r10,qword ptr [rsi+08h]   ; 
         adox   r8,qword ptr [rdi]            ; 
         lea    ecx,[rcx+08h]                 ; 
         mov    qword ptr [rdi],r8            ; 
         adcx   r10,r9                        ; 
         mulx   r9,r8,qword ptr [rsi+010h]    ; 
         adcx   r8,r11                        ; 
         adox   r10,qword ptr [rdi+08h]       ; 
         mov    qword ptr [rdi+08h],r10       ; 
         mulx   r11,r10,qword ptr [rsi+018h]  ; 
         lea    rsi,[rsi+040h]                ; 
         adcx   r10,r9                        ; 
         adox   r8,qword ptr [rdi+010h]       ; 
         mov    qword ptr [rdi+010h],r8       ; 
         mulx   r9,r8,qword ptr [rsi-020h]    ; 
         adox   r10,qword ptr [rdi+018h]      ; 
         adcx   r8,r11                        ; 
         mov    qword ptr [rdi+018h],r10      ; 
         mulx   r11,r10,qword ptr [rsi-018h]  ; 
         adcx   r10,r9                        ; 
         adox   r8,qword ptr [rdi+020h]       ; 
         mov    qword ptr [rdi+020h],r8       ; 
         mulx   r9,r8,qword ptr [rsi-010h]    ; 
         adox   r10,qword ptr [rdi+028h]      ; 
         adcx   r8,r11                        ; 
         mov    qword ptr [rdi+028h],r10      ; 
         adox   r8,qword ptr [rdi+030h]       ; 
         mulx   r11,r10,qword ptr [rsi-08h]   ; 
         mov    qword ptr [rdi+030h],r8       ; 
         lea    rdi,[rdi+040h]                ; 
         adcx   r10,r9                        ; 
         mulx   r9,r8,qword ptr [rsi]         ; 
         jmp    l_0410                        ; 
         ALIGN  16                            ;
l_04D7:  adox   r8,qword ptr [rdi]            ; 
         adox   r9,rcx                        ; 
Lf1:     mov    qword ptr [rdi],r8            ; 
         adc    r9,rcx                        ; 
         mov    qword ptr [rdi+08h],r9        ; 
         lea    rsi,[rsi+rbx*8]               ; 
         mov    ecx,ebx                       ; 
         lea    rbx,[rbx+08h]                 ; 
         lea    rdi,[rdi+rbx*8-038h]          ; 
         mov    r9,qword ptr [rsi-010h]       ; 
         mov    rdx,qword ptr [rsi-08h]       ; 
         shrx   r8,r9,rax                     ; 
         sarx   r9,r9,rax                     ; 
         and    r9,rdx                        ; 
         mulx   r11,r10,rdx                   ; 
         lea    rdx,[r8+rdx*2]                ; 
         adcx   r10,r9                        ; 
         mulx   r9,r8,qword ptr [rsi]         ; 
         adox   r10,qword ptr [rdi-08h]       ; 
         adcx   r8,r11                        ; 
         mov    qword ptr [rdi-08h],r10       ; 
         jmp    l_0423                        ; 
;         ALIGN  16                            ; had to remove this or next 'jrcxz' would have been too far away (by 3 bytes)
l_0540:  adox   r10,qword ptr [rdi-08h]       ; 
         adcx   r8,r11                        ; 
         mov    qword ptr [rdi-08h],r10       ; 
         jrcxz  l_04D7                        ; 
         mulx   r11,r10,qword ptr [rsi+08h]   ; 
         adox   r8,qword ptr [rdi]            ; 
         lea    ecx,[rcx+08h]                 ; 
         mov    qword ptr [rdi],r8            ; 
         adcx   r10,r9                        ; 
         mulx   r9,r8,qword ptr [rsi+010h]    ; 
         adcx   r8,r11                        ; 
         adox   r10,qword ptr [rdi+08h]       ; 
         mov    qword ptr [rdi+08h],r10       ; 
         mulx   r11,r10,qword ptr [rsi+018h]  ; 
         lea    rsi,[rsi+040h]                ; 
         adcx   r10,r9                        ; 
         adox   r8,qword ptr [rdi+010h]       ; 
         mov    qword ptr [rdi+010h],r8       ; 
         mulx   r9,r8,qword ptr [rsi-020h]    ; 
         adox   r10,qword ptr [rdi+018h]      ; 
         adcx   r8,r11                        ; 
         mov    qword ptr [rdi+018h],r10      ; 
         mulx   r11,r10,qword ptr [rsi-018h]  ; 
         adcx   r10,r9                        ; 
         adox   r8,qword ptr [rdi+020h]       ; 
         mov    qword ptr [rdi+020h],r8       ; 
         mulx   r9,r8,qword ptr [rsi-010h]    ; 
         adox   r10,qword ptr [rdi+028h]      ; 
         adcx   r8,r11                        ; 
         mov    qword ptr [rdi+028h],r10      ; 
l_05E2:  adox   r8,qword ptr [rdi+030h]       ; 
         mulx   r11,r10,qword ptr [rsi-08h]   ; 
         mov    qword ptr [rdi+030h],r8       ; 
         lea    rdi,[rdi+040h]                ; 
         adcx   r10,r9                        ; 
         mulx   r9,r8,qword ptr [rsi]         ; 
         jmp    l_0540                        ; 
         ALIGN  16                            ;
l_0607:  adox   r8,qword ptr [rdi]            ; 
         adox   r9,rcx                        ; 
         ALIGN  16                            ;
Lf2:     mov    qword ptr [rdi],r8            ; 
         adc    r9,rcx                        ; 
         mov    qword ptr [rdi+08h],r9        ; 
         lea    rsi,[rsi+rbx*8]               ; 
         or     ecx,ebx                       ; 
         je     l_0BA7                        ; 
         lea    rdi,[rdi+rbx*8-038h]          ; 
         mov    r11,qword ptr [rsi-018h]      ; 
         mov    rdx,qword ptr [rsi-010h]      ; 
         shrx   r10,r11,rax                   ; 
         sarx   r11,r11,rax                   ; 
         and    r11,rdx                       ; 
         mulx   r9,r8,rdx                     ; 
         lea    rdx,[r10+rdx*2]               ; 
         adcx   r8,r11                        ; 
         jmp    l_05E2                        ; 
         ALIGN  16                            ; 
l_0660:  adox   r10,qword ptr [rdi-08h]       ; 
         adcx   r8,r11                        ; 
         mov    qword ptr [rdi-08h],r10       ; 
         jrcxz  l_0607                        ; 
         mulx   r11,r10,qword ptr [rsi+08h]   ; 
         adox   r8,qword ptr [rdi]            ; 
         lea    ecx,[rcx+08h]                 ; 
         mov    qword ptr [rdi],r8            ; 
         adcx   r10,r9                        ; 
         mulx   r9,r8,qword ptr [rsi+010h]    ; 
         adcx   r8,r11                        ; 
         adox   r10,qword ptr [rdi+08h]       ; 
         mov    qword ptr [rdi+08h],r10       ; 
         mulx   r11,r10,qword ptr [rsi+018h]  ; 
         lea    rsi,[rsi+040h]                ; 
         adcx   r10,r9                        ; 
         adox   r8,qword ptr [rdi+010h]       ; 
         mov    qword ptr [rdi+010h],r8       ; 
         mulx   r9,r8,qword ptr [rsi-020h]    ; 
         adox   r10,qword ptr [rdi+018h]      ; 
         adcx   r8,r11                        ; 
         mov    qword ptr [rdi+018h],r10      ; 
         mulx   r11,r10,qword ptr [rsi-018h]  ; 
         adcx   r10,r9                        ; 
         adox   r8,qword ptr [rdi+020h]       ; 
         mov    qword ptr [rdi+020h],r8       ; 
l_06EB:  mulx   r9,r8,qword ptr [rsi-010h]    ; 
         adox   r10,qword ptr [rdi+028h]      ; 
         adcx   r8,r11                        ; 
         mov    qword ptr [rdi+028h],r10      ; 
         adox   r8,qword ptr [rdi+030h]       ; 
         mulx   r11,r10,qword ptr [rsi-08h]   ; 
         mov    qword ptr [rdi+030h],r8       ; 
         lea    rdi,[rdi+040h]                ; 
         adcx   r10,r9                        ; 
         mulx   r9,r8,qword ptr [rsi]         ; 
         jmp    l_0660                        ; 
         ALIGN  16                            ;
l_0727:  adox   r8,qword ptr [rdi]            ; 
         adox   r9,rcx                        ; 
         ALIGN  16                            ;
Lf3:     mov    qword ptr [rdi],r8            ; 
         adc    r9,rcx                        ; 
         mov    qword ptr [rdi+08h],r9        ; 
         lea    rsi,[rsi+rbx*8]               ; 
         mov    ecx,ebx                       ; 
         lea    rdi,[rdi+rbx*8-038h]          ; 
         mov    r9,qword ptr [rsi-020h]       ; 
         mov    rdx,qword ptr [rsi-018h]      ; 
         shrx   r8,r9,rax                     ; 
         sarx   r9,r9,rax                     ; 
         and    r9,rdx                        ; 
         mulx   r11,r10,rdx                   ; 
         lea    rdx,[r8+rdx*2]                ; 
         adcx   r10,r9                        ; 
         jmp    l_06EB                        ; 
         ALIGN  16                            ; 
l_0780:  adox   r10,qword ptr [rdi-08h]       ; 
         adcx   r8,r11                        ; 
         mov    qword ptr [rdi-08h],r10       ; 
         jrcxz  l_0727                        ; 
         mulx   r11,r10,qword ptr [rsi+08h]   ; 
         adox   r8,qword ptr [rdi]            ; 
         lea    ecx,[rcx+08h]                 ; 
         mov    qword ptr [rdi],r8            ; 
         adcx   r10,r9                        ; 
         mulx   r9,r8,qword ptr [rsi+010h]    ; 
         adcx   r8,r11                        ; 
         adox   r10,qword ptr [rdi+08h]       ; 
         mov    qword ptr [rdi+08h],r10       ; 
         mulx   r11,r10,qword ptr [rsi+018h]  ; 
         lea    rsi,[rsi+040h]                ; 
         adcx   r10,r9                        ; 
         adox   r8,qword ptr [rdi+010h]       ; 
         mov    qword ptr [rdi+010h],r8       ; 
         mulx   r9,r8,qword ptr [rsi-020h]    ; 
         adox   r10,qword ptr [rdi+018h]      ; 
         adcx   r8,r11                        ; 
         mov    qword ptr [rdi+018h],r10      ; 
l_07F4:  mulx   r11,r10,qword ptr [rsi-018h]  ; 
         adcx   r10,r9                        ; 
         adox   r8,qword ptr [rdi+020h]       ; 
         mov    qword ptr [rdi+020h],r8       ; 
         mulx   r9,r8,qword ptr [rsi-010h]    ; 
         adox   r10,qword ptr [rdi+028h]      ; 
         adcx   r8,r11                        ; 
         mov    qword ptr [rdi+028h],r10      ; 
         adox   r8,qword ptr [rdi+030h]       ; 
         mulx   r11,r10,qword ptr [rsi-08h]   ; 
         mov    qword ptr [rdi+030h],r8       ; 
         lea    rdi,[rdi+040h]                ; 
         adcx   r10,r9                        ; 
         mulx   r9,r8,qword ptr [rsi]         ; 
         jmp    l_0780                        ; 
         ALIGN  16                            ;
l_0847:  adox   r8,qword ptr [rdi]            ; 
         adox   r9,rcx                        ; 
         ALIGN  16                            ;
Lf4:     mov    qword ptr [rdi],r8            ; 
         adc    r9,rcx                        ; 
         mov    qword ptr [rdi+08h],r9        ; 
         lea    rsi,[rsi+rbx*8]               ; 
         mov    ecx,ebx                       ; 
         lea    rdi,[rdi+rbx*8-038h]          ; 
         mov    r11,qword ptr [rsi-028h]      ; 
         mov    rdx,qword ptr [rsi-020h]      ; 
         shrx   r10,r11,rax                   ; 
         sarx   r11,r11,rax                   ; 
         and    r11,rdx                       ; 
         mulx   r9,r8,rdx                     ; 
         lea    rdx,[r10+rdx*2]               ; 
         adcx   r8,r11                        ; 
         jmp    l_07F4                        ; 
         ALIGN  16                            ; 
l_08A0:  adox   r10,qword ptr [rdi-08h]       ; 
         adcx   r8,r11                        ; 
         mov    qword ptr [rdi-08h],r10       ; 
         jrcxz  l_0847                        ; 
         mulx   r11,r10,qword ptr [rsi+08h]   ; 
         adox   r8,qword ptr [rdi]            ; 
         lea    ecx,[rcx+08h]                 ; 
         mov    qword ptr [rdi],r8            ; 
         adcx   r10,r9                        ; 
         mulx   r9,r8,qword ptr [rsi+010h]    ; 
         adcx   r8,r11                        ; 
         adox   r10,qword ptr [rdi+08h]       ; 
         mov    qword ptr [rdi+08h],r10       ; 
         mulx   r11,r10,qword ptr [rsi+018h]  ; 
         lea    rsi,[rsi+040h]                ; 
         adcx   r10,r9                        ; 
         adox   r8,qword ptr [rdi+010h]       ; 
         mov    qword ptr [rdi+010h],r8       ; 
l_08FD:  mulx   r9,r8,qword ptr [rsi-020h]    ; 
         adox   r10,qword ptr [rdi+018h]      ; 
         adcx   r8,r11                        ; 
         mov    qword ptr [rdi+018h],r10      ; 
         mulx   r11,r10,qword ptr [rsi-018h]  ; 
         adcx   r10,r9                        ; 
         adox   r8,qword ptr [rdi+020h]       ; 
         mov    qword ptr [rdi+020h],r8       ; 
         mulx   r9,r8,qword ptr [rsi-010h]    ; 
         adox   r10,qword ptr [rdi+028h]      ; 
         adcx   r8,r11                        ; 
         mov    qword ptr [rdi+028h],r10      ; 
         adox   r8,qword ptr [rdi+030h]       ; 
         mulx   r11,r10,qword ptr [rsi-08h]   ; 
         mov    qword ptr [rdi+030h],r8       ; 
         lea    rdi,[rdi+040h]                ; 
         adcx   r10,r9                        ; 
         mulx   r9,r8,qword ptr [rsi]         ; 
         jmp    l_08A0                        ; 
         ALIGN  16                            ;
l_0967:  adox   r8,qword ptr [rdi]            ; 
         adox   r9,rcx                        ; 
         ALIGN  16                            ;
Lf5:     mov    qword ptr [rdi],r8            ; 
         adc    r9,rcx                        ; 
         mov    qword ptr [rdi+08h],r9        ; 
         lea    rsi,[rsi+rbx*8]               ; 
         mov    ecx,ebx                       ; 
         lea    rdi,[rdi+rbx*8-038h]          ; 
         mov    r9,qword ptr [rsi-030h]       ; 
         mov    rdx,qword ptr [rsi-028h]      ; 
         shrx   r8,r9,rax                     ; 
         sarx   r9,r9,rax                     ; 
         and    r9,rdx                        ; 
         mulx   r11,r10,rdx                   ; 
         lea    rdx,[r8+rdx*2]                ; 
         adcx   r10,r9                        ; 
         jmp    l_08FD                        ; 
         ALIGN  16                            ; 
l_09C0:  adox   r10,qword ptr [rdi-08h]       ; 
         adcx   r8,r11                        ; 
         mov    qword ptr [rdi-08h],r10       ; 
         jrcxz  l_0967                        ; 
         mulx   r11,r10,qword ptr [rsi+08h]   ; 
         adox   r8,qword ptr [rdi]            ; 
         lea    ecx,[rcx+08h]                 ; 
         mov    qword ptr [rdi],r8            ; 
         adcx   r10,r9                        ; 
         mulx   r9,r8,qword ptr [rsi+010h]    ; 
         adcx   r8,r11                        ; 
         adox   r10,qword ptr [rdi+08h]       ; 
         mov    qword ptr [rdi+08h],r10       ; 
         mulx   r11,r10,qword ptr [rsi+018h]  ; 
         lea    rsi,[rsi+040h]                ; 
l_0A0C:  adcx   r10,r9                        ; 
         adox   r8,qword ptr [rdi+010h]       ; 
         mov    qword ptr [rdi+010h],r8       ; 
         mulx   r9,r8,qword ptr [rsi-020h]    ; 
         adox   r10,qword ptr [rdi+018h]      ; 
         adcx   r8,r11                        ; 
         mov    qword ptr [rdi+018h],r10      ; 
         mulx   r11,r10,qword ptr [rsi-018h]  ; 
         adcx   r10,r9                        ; 
         adox   r8,qword ptr [rdi+020h]       ; 
         mov    qword ptr [rdi+020h],r8       ; 
         mulx   r9,r8,qword ptr [rsi-010h]    ; 
         adox   r10,qword ptr [rdi+028h]      ; 
         adcx   r8,r11                        ; 
         mov    qword ptr [rdi+028h],r10      ; 
         adox   r8,qword ptr [rdi+030h]       ; 
         mulx   r11,r10,qword ptr [rsi-08h]   ; 
         mov    qword ptr [rdi+030h],r8       ; 
         lea    rdi,[rdi+040h]                ; 
         adcx   r10,r9                        ; 
         mulx   r9,r8,qword ptr [rsi]         ; 
         jmp    l_09C0                        ; 
         ALIGN  16                            ;
l_0A87:  adox   r8,qword ptr [rdi]            ; 
         adox   r9,rcx                        ; 
         ALIGN  16                            ;
Lf6:     mov    qword ptr [rdi],r8            ; 
         adc    r9,rcx                        ; 
         mov    qword ptr [rdi+08h],r9        ; 
         lea    rsi,[rsi+rbx*8]               ; 
         mov    ecx,ebx                       ; 
         lea    rdi,[rdi+rbx*8-038h]          ; 
         mov    r11,qword ptr [rsi-038h]      ; 
         mov    rdx,qword ptr [rsi-030h]      ; 
         shrx   r10,r11,rax                   ; 
         sarx   r11,r11,rax                   ; 
         and    r11,rdx                       ; 
         mulx   r9,r8,rdx                     ; 
         lea    rdx,[r10+rdx*2]               ; 
         adcx   r8,r11                        ; 
         mulx   r11,r10,qword ptr [rsi-028h]  ; 
         jmp    l_0A0C                        ; 
         ALIGN  16                            ; 
l_0AE0:  adox   r10,qword ptr [rdi-08h]       ; 
         adcx   r8,r11                        ; 
         mov    qword ptr [rdi-08h],r10       ; 
         jrcxz  l_0A87                        ; 
         mulx   r11,r10,qword ptr [rsi+08h]   ; 
         adox   r8,qword ptr [rdi]            ; 
         lea    ecx,[rcx+08h]                 ; 
         mov    qword ptr [rdi],r8            ; 
l_0B05:  adcx   r10,r9                        ; 
         mulx   r9,r8,qword ptr [rsi+010h]    ; 
         adcx   r8,r11                        ; 
         adox   r10,qword ptr [rdi+08h]       ; 
         mov    qword ptr [rdi+08h],r10       ; 
         mulx   r11,r10,qword ptr [rsi+018h]  ; 
         lea    rsi,[rsi+040h]                ; 
         adcx   r10,r9                        ; 
         adox   r8,qword ptr [rdi+010h]       ; 
         mov    qword ptr [rdi+010h],r8       ; 
         mulx   r9,r8,qword ptr [rsi-020h]    ; 
         adox   r10,qword ptr [rdi+018h]      ; 
         adcx   r8,r11                        ; 
         mov    qword ptr [rdi+018h],r10      ; 
         mulx   r11,r10,qword ptr [rsi-018h]  ; 
         adcx   r10,r9                        ; 
         adox   r8,qword ptr [rdi+020h]       ; 
         mov    qword ptr [rdi+020h],r8       ; 
         mulx   r9,r8,qword ptr [rsi-010h]    ; 
         adox   r10,qword ptr [rdi+028h]      ; 
         adcx   r8,r11                        ; 
         mov    qword ptr [rdi+028h],r10      ; 
         adox   r8,qword ptr [rdi+030h]       ; 
         mulx   r11,r10,qword ptr [rsi-08h]   ; 
         mov    qword ptr [rdi+030h],r8       ; 
         lea    rdi,[rdi+040h]                ; 
         adcx   r10,r9                        ; 
         mulx   r9,r8,qword ptr [rsi]         ; 
         jmp    l_0AE0                        ; 
         ALIGN  16                            ;
l_0BA7:  lea    rdi,[rdi-040h]                ; 
         mov    r11,qword ptr [rsi-018h]      ; 
         mov    rdx,qword ptr [rsi-010h]      ; 
         shrx   r10,r11,rax                   ; 
         sarx   r11,r11,rax                   ; 
         and    r11,rdx                       ; 
         mulx   r9,r8,rdx                     ; 
         lea    rdx,[r10+rdx*2]               ; 
         adcx   r8,r11                        ; 
         adox   r8,qword ptr [rdi+038h]       ; 
         mulx   r11,r10,qword ptr [rsi-08h]   ; 
         mov    qword ptr [rdi+038h],r8       ; 
         adcx   r10,r9                        ; 
         mulx   r9,rbx,qword ptr [rsi]        ; 
         adox   r10,qword ptr [rdi+040h]      ; 
         adcx   rbx,r11                       ; 
         mov    qword ptr [rdi+040h],r10      ; 
         adox   rbx,qword ptr [rdi+048h]      ; 
         adox   r9,rcx                        ; 
         adc    r9,rcx                        ; 
         mov    qword ptr [rdi+050h],r9       ; 
         mov    r9,qword ptr [rsi-010h]       ; 
         mov    rdx,qword ptr [rsi-08h]       ; 
         shrx   r8,r9,rax                     ; 
         sarx   r9,r9,rax                     ; 
         and    r9,rdx                        ; 
         mulx   r11,r10,rdx                   ; 
         lea    rdx,[r8+rdx*2]                ; 
         adcx   r10,r9                        ; 
         mulx   rax,r8,qword ptr [rsi]        ; 
         adox   r10,rbx                       ; 
         adcx   r8,r11                        ; 
         mov    qword ptr [rdi+048h],r10      ; 
         adox   r8,qword ptr [rdi+050h]       ; 
         adox   rax,rcx                       ; 
         mov    qword ptr [rdi+050h],r8       ; 
         adc    rax,rcx                       ; 
         mov    r11,qword ptr [rsi-08h]       ; 
         mov    rdx,qword ptr [rsi]           ; 
         sar    r11,03fh                      ; 
         and    r11,rdx                       ; 
         mulx   r9,r8,rdx                     ; 
         adcx   r8,r11                        ; 
         adox   r8,rax                        ; 
         mov    qword ptr [rdi+058h],r8       ; 
         adcx   r9,rcx                        ; 
         adox   r9,rcx                        ; 
         mov    qword ptr [rdi+060h],r9       ; 
         pop    rbx                           ; 
         pop    rsi                           ; SysV-to-MSVC ABI (restore rsi)
         pop    rdi                           ; SysV-to-MSVC ABI (restore rdi)
         ret                                  ; 
                                              ;
         ALIGN  16                            ;

Lmtab:
         dq     offset Lmf7
         dq     offset Lmf0
         dq     offset Lmf1
         dq     offset Lmf2
         dq     offset Lmf3
         dq     offset Lmf4
         dq     offset Lmf5
         dq     offset Lmf6

Latab:
         dq     offset Lf6
         dq     offset Lf7
         dq     offset Lf0
         dq     offset Lf1
         dq     offset Lf2
         dq     offset Lf3
         dq     offset Lf4
         dq     offset Lf5

__gmpn_sqr_basecase ENDP

                   END
